### ISSUE TITLE
[Tracker] Full control of OSBS builds

### ISSUE THREAD

**Issue by goldmann** [cekit/cekit#165]
### Required

- [x] Allow to specify user while executing the OSBS build (#163)
- [x] Allow to override dist-git branch (#175)
    * Use case: use of `private-` branches
    * If we do this, we should probably also make it possible to override the repo name.
- [x] Ability to override `FROM` (#175)
    * Use case: scratch builds depends on another scratch build
- [x] Allow to specify `--nowait` parameter in `rhpkg`

### Nice to have

- [ ] Write task info to a text file (#183)
    * We could use brew API directly to connect and get detailed information about the task progress and/or result
