### ISSUE TITLE
Review caching

### ISSUE THREAD

**Issue by goldmann** [cekit/cekit#361]
- [x] `cekit-cache` command without parameters prints nothing
- [x] Caching local file should not use involve usage of cacher, even if defined
- [x] Error handling - in case an error occurs while caching artifact, leftovers should be cleaned up.
- [x] Artifact added to cache should have computed checksum for every supported algorithm
  * This also helps with the artifact duplication if the `add` command was run on with the same artifact, but with different algorithms.

**Comment by ochaloup** [comment]
`cekit-cache -h` command could be enhanced as well. There is currently no info about how to add the checksum (argument `--md5` is not mentioned in the help message). Currently it's pretty important for the `add` command to succeed.

**Comment by goldmann** [comment]
This is a valid point. I think this fits well into #364 too.

**Comment by goldmann** [comment]
The `cekit-cache` CLI was rewritten as part of https://github.com/cekit/cekit/pull/412.
