### ISSUE TITLE
Review documentation

### ISSUE THREAD

**Issue by goldmann** [cekit/cekit#367]
Test documentation needs to be reviewed and updated, tracked in: https://github.com/cekit/cekit/issues/232

Whole documentation needs to be reviewed, typos needs to be fixed. If something needs to be clarified, it should be.

- [x] Update documentation for artifacts definition #418
- [x] Document how modules are combined together and squashed later #365 
- [x] Prepare getting started guide with basic example #266 
- [x] Update test documentation #232 
- [x]  Review caching documentation #449
- [x] Update dependencies section https://github.com/cekit/cekit/commit/1a9be46a1e4d52e711689cdaf7418439f5609495
- [x] Document how build process works #447
- [x] Contribution guide, https://github.com/cekit/cekit/pull/477

**Comment by goldmann** [comment]
A nice to have would be a warning in the development docs that the content is about unreleased version.

**Comment by rnc** [comment]
http://docs.cekit.io/en/develop/descriptor/image.html#labels refers to https://github.com/projectatomic/ContainerApplicationGenericLabels which is out of date.

**Comment by goldmann** [comment]
Development process was moved to 3.1: #369
