### ISSUE TITLE
3.0 Release Tracker

### ISSUE THREAD

**Issue by goldmann** [cekit/cekit#481]
- [x]  Merge develop with master
- [x] Tag repository
- [x] Push a release to https://pypi.org/project/cekit/
- [x] Polish release notes
- [x] Build and submit in Bodhi RPMs for Fedora and EPEL
- [x] Write announcement blog post
- [x] Announce on Twitter
