### ISSUE TITLE
3.0.1 release tracker

### ISSUE THREAD

**Issue by goldmann** [cekit/cekit#500]
- [x] Cherry-pick required changes
- [x] Tag repository
- [x] Prepare release notes
- [x] Push a release to https://pypi.org/project/cekit/
- [x] Build and submit in Bodhi RPMs for Fedora and EPEL
- [x] Write announcement blog post
- [x] Announce on Twitter
