### ISSUE TITLE
Release 3.1.0 tracker

### ISSUE THREAD

**Issue by goldmann** [cekit/cekit#522]
- [x] Tag repository
- [x] Prepare release notes
- [x] Push a release to https://pypi.org/project/cekit/
- [x] Build and submit in Bodhi RPMs for Fedora and EPEL
- [x] Write announcement blog post
- [x] Announce on Twitter
