### ISSUE TITLE
Release 3.2.0 tracker

### ISSUE THREAD

**Issue by goldmann** [cekit/cekit#550]
- [x] Tag repository
- [x] Prepare release notes
- [x] Push a release to https://pypi.org/project/cekit/
- [x] Build and submit in Bodhi RPMs for Fedora and EPEL
- [x] Write announcement blog post external
- [x] Write announcement blog post internal
- [x] Announce on Twitter
- [x] Announce on ML's
